##
## DOES NOT WORK, GIVES CIRCULAR DEPENDENCIES...
##
#  links:
#    - discovery2
#  command: java -jar -Dspring.profiles.active=docker1 microservices/support/discovery-server/build/libs/discovery-server-0.0.1-SNAPSHOT.jar
#  
#discovery2:
#  image: magnus-larsson/spring-boot
#  restart: always
#  ports:
#    - "8762:8762"
#  volumes:
#    - $PWD:/data
#  links:
#    - discovery
#  command: java -jar -Dspring.profiles.active=docker2 microservices/support/discovery-server/build/libs/discovery-server-0.0.1-SNAPSHOT.jar

version: '2'

services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
  #    - "5672:5672"
      - "15672:15672"

  discovery:
    build: microservices/support/discovery-server
    restart: always
    ports:
      - "8761:8761"

  config:
    build: microservices/support/config-server
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - $PWD/../blog-microservices-config:/config-repo

  auth:
    build: microservices/support/auth-server
    restart: always
    ports:
      - "9999:9999"

  #turbine:
  #  image: magnuslarsson/ms-blog-turbine
  ##  volumes:
  ##    - $PWD/logs:/logs

  pro:
    build: microservices/core/product-service
    restart: always

  monitor:
    build: microservices/support/monitor-dashboard
    restart: always
    ports:
      - "7979:7979"

  edge:
    build: microservices/support/edge-server
    restart: always
    ports:
      - "443:8765"
